### ISSUE TITLE
Subject-Offering

### ISSUE THREAD

**Issue by batiquinianchris** [aaajii/maryknoll-system#12]
![2](https://user-images.githubusercontent.com/29658188/36267154-321ef834-12ae-11e8-9db3-08d8090ae56b.PNG)

Instead na apil sa forms or input ang Year Level, i suggest na murag filter nlng sya. So bali ang mga subject lang under that Year Level ang mugawas sa dropdown sa Subject Name na field.

**Comment by aaajii** [comment]
You can try this before sending the 'form' object to the context:
```
    selected_curr = Curriculum.objects.get(year_level=<insert desired year_level here>)
    form.fields["subject"].queryset = Subject.objects.filter(curriculum=selected_curr)
```
