### ISSUE TITLE
Section_Enrollee Table--not necessary(?)

### ISSUE THREAD

**Issue by batiquinianchris** [aaajii/maryknoll-system#22]
![concern1](https://user-images.githubusercontent.com/29658188/37557580-94bb9358-2a41-11e8-83e5-fed20d31f928.PNG)

Jim wla nalang guro ni na model since naa nay section an attribute ang enrollment

**Comment by aaajii** [comment]
![image](https://user-images.githubusercontent.com/27285268/37557815-18cf465a-2a45-11e8-9bca-987c4162a993.png)

Check registrar.models.Enrollment

**Comment by aaajii** [comment]
next time try to fetch and merge before you start working
